CREATE TABLE GUESTBOOK (
NUM NUMBER(5),
NAME VARCHAR2(100),
SUBJECT VARCHAR2(300),
CONTENT VARCHAR2(2000),
WRITEDATE DATE,
CONSTRAINT PK_GUESTBOOK PRIMARY KEY (NUM));

CREATE SEQUENCE SEQ_GUESTBOOK_NUM
MINVALUE 0
START WITH 0
INCREMENT BY 1;

SELECT * FROM GUESTBOOK;

SELECT * FROM GUESTBOOK WHERE NUM=1;

INSERT INTO GUESTBOOK VALUES(
SEQ_GUESTBOOK_NUM.NEXTVAL,
'김선생',
'김선생의 메모',
'김선생의 메모내용',
SYSDATE);

UPDATE GUESTBOOK SET
NAME='박선생',
SUBJECT='박선생의 메모',
CONTENT='박선생의 메모내용',
WRITEDATE=SYSDATE
WHERE NUM=1;

DELETE FROM GUESTBOOK WHERE NUM=1;


-------------------------------- customer -------------------------
CREATE TABLE CUSTOMER(
CUSTOMERID NUMBER(5) PRIMARY KEY,
ID VARCHAR2(50) UNIQUE NOT NULL,
NAME VARCHAR2(50),
PASSWORD VARCHAR2(50),
POSTCODE VARCHAR2(5),
ADDRESS VARCHAR2(100),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(100),
EMAIL VARCHAR2(100));

CREATE SEQUENCE SEQ_CUSTOMER_ID;
SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER WHERE CUSTOMERID=2;

SELECT * FROM CUSTOMER WHERE ID='USERID2';

SELECT * FROM CUSTOMER WHERE NAME LIKE '%종우%';

SELECT count(*) cnt FROM CUSTOMER WHERE ID='shoong';

INSERT INTO CUSTOMER VALUES(
SEQ_CUSTOMER_ID.NEXTVAL,
'DELETEID9',
'HAHA',
'SDFSDF',
'05123',
'서울',
'100동',
'010-1111-1111',
'SHOONG199@GMAIL.COM');

UPDATE CUSTOMER SET
ID='USERID2',
NAME='HAHA2',
PASSWORD='SDFSDF2',
POSTCODE='05111',
ADDRESS='서울2',
ADDRESS2='100동2',
PHONE='010-1111-2222',
EMAIL='DDD@GMAIL.COM'
WHERE CUSTOMERID=2;

DELETE FROM CUSTOMER WHERE CUSTOMERID=21;

DROP TABLE CUSTOMER;
CREATE SEQUENCE SEQ_CUSTOMER_ID;


--------------------------------------
DROP TABLE BOOK;

-- BOOK TABLE
CREATE TABLE BOOK(
BOOKID NUMBER(5) PRIMARY KEY,
BOOKNAME VARCHAR2(200),
PUBLISHER VARCHAR2(200),
PRICE NUMBER(6),
DESCRIPTION VARCHAR2(1000));

SELECT SEQ_BOOK.CURRVAL FROM DUAL;



CREATE SEQUENCE SEQ_BOOK;

INSERT INTO BOOK VALUES(
SEQ_BOOK.NEXTVAL,
'자바프로그래밍',
'자바출판사',
20,
'좋은 자바책');

INSERT INTO BOOK VALUES(
SEQ_BOOK.NEXTVAL,
'스프링프로그래밍',
'스프링출판사',
30,
'좋은 스프링책');
-- ORDER TABLE
ALTER TABLE ORDERS MODIFY(AMOUNT NUMBER(7));
CREATE TABLE ORDERS(
ORDERID NUMBER(5) PRIMARY KEY,
ORDERDATE DATE,
AMOUNT NUMBER(7),
SENDYN VARCHAR2(1),
PAYOPTION NUMBER(2),
CUSTOMERID NUMBER(5) REFERENCES CUSTOMER(CUSTOMERID));

CREATE SEQUENCE SEQ_ORDERS;

INSERT INTO ORDERS VALUES(
SEQ_ORDERS.NEXTVAL,
SYSDATE,
80,
'N',
1,
11
);



CREATE TABLE ORDERITEM(
ORDERITEMID NUMBER(5) PRIMARY KEY,
QUANTITY NUMBER(3),
BOOKID NUMBER(5) REFERENCES BOOK(BOOKID),
ORDERID NUMBER(5) REFERENCES ORDERS(ORDERID)
);

CREATE SEQUENCE SEQ_ORDERITEM;

INSERT INTO ORDERITEM VALUES (
SEQ_ORDERITEM.NEXTVAL,
1,
2,
2);

INSERT INTO ORDERITEM VALUES (
SEQ_ORDERITEM.NEXTVAL,
2,
3,
2);

INSERT INTO
ORDERS VALUES(
SEQ_ORDERS.NEXTVAL,
'2018-04-01',
270,
'N',
1,
11
);
INSERT INTO ORDERITEM VALUES (
SEQ_ORDERITEM.NEXTVAL,
6,
2,
SEQ_ORDERS.CURRVAL);

INSERT INTO ORDERITEM VALUES (
SEQ_ORDERITEM.NEXTVAL,
5,
3,
SEQ_ORDERS.CURRVAL);



SELECT SEQ_ORDERS.nextval,SEQ_ORDERS.nextval FROM DUAL;
SELECT SEQ_ORDERITEM.CURRVAL FROM DUAL;

SELECT SEQ_CUSTOMER_ID.CURRVAL FROM DUAL;

SELECT * FROM ORDERS WHERE CUSTOMERID=23 AND ORDERDATE >= ADD_MONTHS(SYSDATE,-8);

SELECT SYSDATE-8 FROM DUAL;
SELECT * FROM BOOK ORDER BY BOOKID DESC;
SELECT * FROM ORDERS;
SELECT * FROM ORDERITEM;
SELECT * FROM CUSTOMER ORDER BY CUSTOMERID DESC;


