CREATE TABLE FILEBD(
ID NUMBER(5) PRIMARY KEY,
WRITER VARCHAR2(20),
TITLE VARCHAR2(50),
SAVEDFILENAME VARCHAR2(2000),
ORIGINALFILENAME VARCHAR2(500)
);

CREATE SEQUENCE SEQ_FILEBD;


INSERT INTO FILEBD VALUES(
SEQ_FILEBD.NEXTVAL,
'JONGWOO',
'JONGWOO PICTURE',
'TEMP.JPG',
'TEMP.JPG');

SELECT * FROM FILEBD ORDER BY ID DESC;

SELECT * FROM FILEBD WHERE ID=3;

DELETE FROM FILEBD WHERE ID=3;